<?php
/**
 * @author    Marcin Frymark
 * @email     contact@alekseon.com
 * @company   Alekseon
 * @website   www.alekseon.com
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head"><?php echo Mage::helper('alekseon_customerComment')->__('Customer Comment') ?></h4></div>
    <fieldset>
        <table class="form-list">
            <tr>
                <td class="value">
                    <?php echo $this->getChildHtml('customer_comment_container') ?>
                </td>
            </tr>
        </table>
    </fieldset>
</div>